<div class="form-editar">
    <h1>editar marca: </h1>
    <form action="editar-marca/<?= $marca->id_marca ?>/update" method="post">
        <input type="text" name="nombre_marca" value="<?= $marca->nombre_marca ?>" required>
        <input type="text" name="contacto" value="<?= $marca->contacto ?>" required>
        <input type="text" name="sede" value="<?= $marca->sede ?>" required>
        <button type="submit">editar</button>
    </form>
</div>