<div class="form-insertar">
    <h1>introducir marca: </h1>
    <form action="agregar-marca" method="POST" enctype="multipart/form-data">
        <input type="text" name="nombre_marca" placeholder="Nombre de Marca" required>
        <input type="text" name="contacto" placeholder="Contacto" required>
        <input type="text" name="sede" placeholder="Sede" required>
        <input type="file" name="imagen_marca" accept=".png, .jpg, .jpeg">
        <button type="submit">crear</button>
    </form>
</div>