<?php require 'templates/layout/header.phtml' ?>
<?php require 'templates/form_insertar_marca.phtml' ?>

<ul class="">
    <?php foreach($marcas as $marca): ?>
        <li class=""><?=$marca->nombre_marca?> <a href="editar-marca/<?=$marca->id_marca?>" class="btn-editar"> O </a> <a href="eliminar-marca/<?=$marca->id_marca?>" class="btn-eliminar"> X </a></li>
    <?php endforeach ?>
</ul>

<?php require 'templates/layout/footer.phtml' ?>