<!DOCTYPE html>
<html lang="es">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <title>Chacinados</title>
</head>
<body>
<header>
    <a href="productos" class="title">chacinados</a>
    <ul class="nav">
        <li class="nav-elem"><a href="productos">productos</a></li>
        <li class="nav-elem"><a href="marcas">marcas</a></li>
        <li class=""><a class="btn-login">iniciar sesión</a></li>
    </ul>
</header>
<main>
